name: Build and Release Flutter APK

# Trigger the workflow on push events to the master branch
on:
  pull_request:
    branches:
      - main

jobs:
  build_and_release:
    name: Build and Release Flutter APK
    runs-on: macos-latest

    steps:
      # Checkout the repository code
      - name: Check out code
        uses: actions/checkout@v2

      # Set up Java Development Kit (JDK)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # Get Flutter packages
      - name: Flutter Pub Get
        run: flutter pub get

      # Build the Flutter APK using the provided action
      - name: Builds - build Flutter APK and create github release
        uses: Dank-del/flutter-build-and-publish-action@v1
