name: Build and Release Flutter APK

on:
  pull_request:
    branches:
      - main  # Trigger on the master branch

jobs:
  build_and_release:
    name: Build and Release Flutter APK
    runs-on: macos-latest

    steps:
      # Step 1: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      # Step 2: Check out the code
      - name: Check out code
        uses: actions/checkout@v2

      # Step 3: Set up Flutter (master channel)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'master'

      # Step 4: Enable macOS desktop support
      - name: Enable macOS desktop support
        run: flutter config --enable-macos-desktop

      # Step 5: Get the required Flutter packages
      - name: Get Flutter packages
        run: flutter pub get

      # Step 6: Build the APK and split by architecture
      - name: Build Flutter APK
        run: flutter build apk --split-per-abi

      # Step 7: Upload built APK files as artifacts
      - name: Upload APK artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Flutter APKs
          path: build/app/outputs/flutter-apk/

      # Step 8: Create a GitHub release with the APKs
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}